[package]
name = "malnet-host"
description = "Host and session management for the Bitfold networking library"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
malnet-core = { workspace = true }
malnet-protocol = { workspace = true }
malnet-peer = { workspace = true }
socket2 = { workspace = true }
crossbeam-channel = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
