[package]
name = "malnet"
description = "A modern, high-performance reliable UDP networking library inspired by ENet & Bitfold, built with Rust."
keywords = ["networking", "udp", "enet", "reliable-udp", "game-networking"]
categories = ["network-programming", "game-development", "asynchronous"]
readme = "../../README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
malnet-core = { workspace = true }
malnet-protocol = { workspace = true }
malnet-peer = { workspace = true }
malnet-host = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

[lints]
workspace = true
